### PR TITLE
Pass partitionKey values appropriate to type of collection and document

### LINKED ISSUE #544: Fail to delete document with error for SQL accounts
Repro steps:
Right click one document and select 'Delete Document', then check whether the document can be deleted or not.

Action: cosmosDB.deleteDocDBDocument
Error type: BadRequest
Error Message: The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.

More Info:
This issue doesn't reproduce in Storage Explorer. The same document can be deleted successfully in Storage Explorer.

Version: 0.6.1-alpha
OS: win32

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #544.

### CODE REVIEW

File: src/docdb/tree/DocDBDocumentTreeItem.ts [hunk 1]
```diff
@@ -103,8 +112,8 @@ export class DocDBDocumentTreeItem implements IAzureTreeItem {
         let value;
         for (let field of fields) {
             value = value ? value[field] : this.document[field];
-            if (!value) {
-                break;
+            if (!value) { //Partition Key exists, but this document doesn't have a value
+                return {};
```
Comment (PrashanthCorp) [inline src/docdb/tree/DocDBDocumentTreeItem.ts]: Not a fan of writing a comment here. Was wondering if it makes more sense to have the following constants: 
```
fixedSizeCollectionPartitionKeyValue = undefined;
UnlimitedCollectionNoPartitionKeyValue= {};
```

The downside being it's only used in one place (here).

File: src/docdb/tree/DocDBDocumentTreeItem.ts [hunk 2]
```diff
@@ -74,11 +79,15 @@ export class DocDBDocumentTreeItem implements IAzureTreeItem {
...
+            let options = { accessCondition: { type: 'IfMatch', condition: newData._etag } };
+            if (this.partitionKeyValue) { //empty object is truth-y
+                options["partitionKey"] = this.partitionKeyValue;
+            }
             this._document = await new Promise<RetrievedDocument>((resolve, reject) => {
                 client.replaceDocument(
                     _self,
                     newData,
-                    { accessCondition: { type: 'IfMatch', condition: newData._etag }, partitionKey: this.partitionKeyValue },
+                    options,
```
Comment (StephenWeatherford) [inline src/docdb/tree/DocDBDocumentTreeItem.ts]: Why'd you remove the access condition?

File: src/docdb/tree/DocDBDocumentTreeItem.ts (hunk 1 above)
Comment (StephenWeatherford) [reply src/docdb/tree/DocDBDocumentTreeItem.ts]: FWIW, don't confuse the idea of fixed vs unlimited with the idea of having a partition key - they might be the same right now in Azure, but not necessarily always.

Comment (StephenWeatherford) [reply src/docdb/tree/DocDBDocumentTreeItem.ts]: Have you thought about whether a partition key with no value is the same as a partition key with {} as the value?

File: src/docdb/tree/DocDBDocumentTreeItem.ts [hunk 3]
```diff
@@ -74,11 +79,15 @@ export class DocDBDocumentTreeItem implements IAzureTreeItem {
             throw new Error(`The "_self" and "_etag" fields are required to update a document`);
         }
         else {
+            let options = { accessCondition: { type: 'IfMatch', condition: newData._etag } };
+            if (this.partitionKeyValue) { //empty object is truth-y
```
Comment (StephenWeatherford) [inline src/docdb/tree/DocDBDocumentTreeItem.ts]: Is it necessary to avoid assigning the partition key value if it's falsy?  How you considered whether 0, empty string, null, etc. are valid partition keys?

File: src/docdb/tree/DocDBDocumentTreeItem.ts (hunk 1 above)
Comment (PrashanthCorp) [reply src/docdb/tree/DocDBDocumentTreeItem.ts]: Yes. Here's what I tested: 
1.Create a doc in the portal, with the partition key value of {}, no quotes. 
2. Open it in the extension. Doc opens fine, empty object has no quotes. 
3. Add another field and update. Open another document and open this document again. Works fine. 
4. Remove the partition key, update. Open another document and open this document again. Works fine. 
5. Add back the empty object partition key value. Update. Open another document and open this document again.  Works fine. 

My hypothesis is that at the server side, documents with either value ({} or no value) are placed in the same partition, and hence it has had no problem locating the document.  But the API expects a value, and the 'no partition key' value happens to be {}. 


Hope this answers the question.

File: src/docdb/tree/DocDBDocumentTreeItem.ts (hunk 3 above)
Comment (PrashanthCorp) [reply src/docdb/tree/DocDBDocumentTreeItem.ts]: This is the error returned for a fixed size collection, if I pass 0, "" or {} as the partitionKey for a collection with no partition key (aka fixed size at this point): 
`Error: Partition key provided either doesn't correspond to definition in the collection or doesn't match partition key field values specified in the document.`

Currently, this is how the API likes to receive partitionKeys: 
1. Key exists for collection, document has a value - give it the value, 
2. Key exists for collection, document has no value - give it an empty object, as outlined [in the node-documentdb workaround](https://github.com/Azure/azure-documentdb-node/issues/222)
3. No key exists (_currently_ corresponds to fixed size) do not give it a partition key value.

Comment (StephenWeatherford) [reply src/docdb/tree/DocDBDocumentTreeItem.ts]: Again, I'm not sure why the "if" is even necessary. If there's no partition key, partitionKeyValue will be undefined, and set as undefined into the options.  I wouldn't expect that to be a problem (although I have seen code where it is).

File: src/docdb/tree/DocDBDocumentTreeItem.ts (hunk 1 above)
Comment (StephenWeatherford) [reply src/docdb/tree/DocDBDocumentTreeItem.ts]: Not fully happy with setting the partition key value to {} when it has no value.  It feels like a hack (although I realize it's Azure that's enforcing it).  Personally it seems like returning undefined makes more sense, and then converting on the update/delete side.  Otherwise you're fixing up a problem at update/delete time by making a chance in code farther away.

But not sure what other effects either of these choices causes - is partitionKey used in other places where the undefined vs {} might be an issue?

If you do go with {} here, then I agree having a constant for it would be a good idea.

File: src/docdb/tree/DocDBDocumentTreeItem.ts (hunk 3 above)
Comment (PrashanthCorp) [reply src/docdb/tree/DocDBDocumentTreeItem.ts]: I placed it there due a typescript compile issue (concerning the type of the partitionKey field). I'll move it back and <any> cast it. Seems better that way.

File: src/docdb/tree/DocDBDocumentTreeItem.ts [hunk 4]
```diff
@@ -103,7 +101,7 @@ export class DocDBDocumentTreeItem implements IAzureTreeItem {
     private getPartitionKeyValue(): string | undefined | Object {
         const partitionKey = this._collection.partitionKey;
         if (!partitionKey) { //Fixed collections -> no partitionKeyValue
-            return undefined;
+            return 0;
```
Comment (StephenWeatherford) [inline src/docdb/tree/DocDBDocumentTreeItem.ts]: ?

Undefined seems the appropriate return value.
