### PR TITLE
Regression fix: Check if globalState has the persisted editors before attempting to load

### LINKED ISSUE #372: “Cannot convert undefined or null to object” occurs after selecting subscription or saving files
Repro Steps:
1. Press F1 on keyboard.
2. Enter "Azure: Select Subscriptions".
3. Select one or more subscriptions.

Expected:
No error occurs.

Actual:
Error occurs.
image

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #372

### CODE REVIEW

File: src/CosmosEditorManager.ts [hunk 1]
```diff
@@ -88,24 +88,28 @@ export class CosmosEditorManager {
...
-        if (editorFilePath) {
-            const editorNode: IAzureNode | undefined = await tree.findNode(persistedEditors[editorFilePath]);
-            let editor: ICosmosEditor;
-            if (editorNode) {
-                if (editorNode.treeItem instanceof MongoCollectionTreeItem) {
-                    editor = new MongoCollectionNodeEditor(<IAzureParentNode<MongoCollectionTreeItem>>editorNode);
-                } else if (editorNode.treeItem instanceof DocDBDocumentTreeItem) {
-                    editor = new DocDBDocumentNodeEditor(<IAzureNode<DocDBDocumentTreeItem>>editorNode);
-                } else if (editorNode.treeItem instanceof MongoDocumentTreeItem) {
-                    editor = new MongoDocumentNodeEditor(<IAzureNode<MongoDocumentTreeItem>>editorNode);
```
Comment (PrashanthCorp) [inline src/CosmosEditorManager.ts]: The diff is actually much smaller. Just inserting an if check in line 91, and else block at 109.

Comment (StephenWeatherford) [reply src/CosmosEditorManager.ts]: View it this way: https://github.com/Microsoft/vscode-cosmosdb/pull/436/files?w=1
