### PR TITLE
Intellisense - Quench errors thrown by parser

### LINKED ISSUE #509: Scrapbook: Running command gives an error if a previous command is erroneous
Example: 
```
db.find({"age" 33}) // No semicolon, no colon separating the key & value in filter
db.findOne({"age": 27}); // Cursor here. This line will be run
```
Running `findOne` will throw an error since we parsing encounters an error in line 1 with text `<missing ':'>`

### LINKED ISSUE #516: Error message in output from code completion typing command
In new scrapbook, type "d"

Error in output:
[Error - 2:02:58 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Error near line 1, column 1, text 'd'. Please check syntax.
  Code: -32603

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #516 

Overload the visitErrorNode function to prevent the usual error throwing. 

Fixes #509 and #392 .

### CODE REVIEW

File: src/mongo/services/mongoScript.ts [hunk 1]
```diff
@@ -64,6 +65,10 @@ class NodeFinder extends MongoVisitor<ParseTree> {
 		super();
 	}
 
+	visitErrorNode(_node: ErrorNode) {
```
Comment (StephenWeatherford) [inline src/mongo/services/mongoScript.ts]: Why should throwing an exception be the normal case?

File: src/mongo/grammar/visitors.ts [hunk 2]
```diff
@@ -63,8 +63,8 @@ export class MongoVisitor<T> implements mongoVisitor<T> {
 		return this.defaultResult(node);
 	}
 
-	visitErrorNode(node: ErrorNode): T {
-		throw new Error(`Error near line ${node._symbol.line}, column ${node.symbol.charPositionInLine + 1}, text '${node.text}'. Please check syntax.`);
+	visitErrorNode(_node: ErrorNode): T {
```
[the remark this answers is not in the document]
Comment (PrashanthCorp) [reply src/mongo/grammar/visitors.ts]: Yup. 
Should I do the fix for #509 in this PR too?

[the remark this answers is not in the document]
Comment (StephenWeatherford) [reply src/mongo/grammar/visitors.ts]: By removing this throw you are regressing the error handling, right?  So yes I would expect the fix to be here.

File: src/mongo/commands.ts [hunk 3]
```diff
@@ -123,6 +127,15 @@ export class MongoScriptDocumentVisitor extends MongoVisitor<MongoCommand[]> {
 		return super.visitArgumentList(ctx);
 	}
 
+	visitErrorNode(node: ErrorNode): MongoCommand[] {
+		const position = new vscode.Position(node._symbol.line - 1, node._symbol.charPositionInLine); // Symbol lines are 1 indexed. Position lines are 0 index
```
Comment (PrashanthCorp) [inline src/mongo/commands.ts]: Need to change index to indexed

File: src/mongo/MongoCommand.ts [hunk 4]
```diff
@@ -11,5 +11,11 @@ export interface MongoCommand {
     collection?: string;
     name: string;
     // tslint:disable-next-line:no-banned-terms
-    arguments?: string[];
+    arguments?: string[],
```
Comment (StephenWeatherford) [inline src/mongo/MongoCommand.ts]: You should use semicolons in an interface

File: src/mongo/MongoCommand.ts [hunk 5]
```diff
@@ -11,5 +11,11 @@ export interface MongoCommand {
...
+    errors?: errorDescription[];
+}
+
+interface errorDescription {
+    position: vscode.Position,
+    text: string
```
Comment (StephenWeatherford) [inline src/mongo/MongoCommand.ts]: message?

File: src/mongo/MongoCommand.ts [hunk 6]
```diff
@@ -11,5 +11,11 @@ export interface MongoCommand {
     collection?: string;
     name: string;
     // tslint:disable-next-line:no-banned-terms
-    arguments?: string[];
+    arguments?: string[],
+    errors?: errorDescription[];
+}
+
+interface errorDescription {
+    position: vscode.Position,
```
Comment (StephenWeatherford) [inline src/mongo/MongoCommand.ts]: ditto

File: src/mongo/commands.ts [hunk 7]
```diff
@@ -38,7 +39,10 @@ export class MongoCommands {
 			if (!database) {
 				throw new Error('Please select a MongoDB database to run against by selecting it in the explorer and selecting the "Connect" context menu item');
 			}
-
+			if (command.errors) {
+				command.errors.sort((a, b) => a.position.character - b.position.character);
```
Comment (StephenWeatherford) [inline src/mongo/commands.ts]: You need to consider the line number, too.

File: src/mongo/commands.ts [hunk 8]
```diff
@@ -38,7 +39,10 @@ export class MongoCommands {
...
+				throw new Error(`Error near line ${command.errors[0].position.line}, column ${command.errors[0].position.character}, text '${command.errors[0].text}'. Please check syntax.`);
```
Comment (StephenWeatherford) [inline src/mongo/commands.ts]: How do you know it has an index 0?  You didn't check.

File: src/mongo/grammar/visitors.ts [hunk 9]
```diff
@@ -63,8 +63,8 @@ export class MongoVisitor<T> implements mongoVisitor<T> {
...
+		return null;
```
Comment (StephenWeatherford) [inline src/mongo/grammar/visitors.ts]: Don't you just not implement visitErrorNode?

File: src/mongo/commands.ts (hunk 7 above)
Comment (StephenWeatherford) [inline src/mongo/commands.ts]: The caller shouldn't be modifying data in the visitor.  You should either clone it first, or better do the sort in the visitor.

**Comment by StephenWeatherford** [comment]
Also need to add some unit tests.  Doesn't need many.

File: src/mongo/grammar/visitors.ts (hunk 9 above)
Comment (PrashanthCorp) [reply src/mongo/grammar/visitors.ts]: This was mainly a reversion to the previous code. 
I currently see both the classes extending it (completionItemProvider and mongo/commands) to have implemented it. 

I see this as a fall back in case the next person is building out a third use case (a function returning nothing won't throw a `member not found` error). I don't feel strongly about this though.

File: src/mongo/MongoCommand.ts [hunk 10]
```diff
@@ -11,11 +11,11 @@ export interface MongoCommand {
     collection?: string;
```
Comment (StephenWeatherford) [inline src/mongo/MongoCommand.ts]: Where be the unit tests?

File: src/mongo/commands.ts [hunk 11]
```diff
@@ -38,7 +39,10 @@ export class MongoCommands {
 			if (!database) {
 				throw new Error('Please select a MongoDB database to run against by selecting it in the explorer and selecting the "Connect" context menu item');
 			}
```
Comment (StephenWeatherford) [inline src/mongo/commands.ts]: Looks like you're way behind.  You need to sync up.

File: src/mongo/commands.ts [hunk 12]
```diff
@@ -40,7 +40,16 @@ export class MongoCommands {
...
 			if (command.errors && command.errors.length > 0) {
-				const err = command.errors.reduce((error1, error2) => error1.position.line - error2.position.line || error1.position.character - error2.position.character <= 0 ? error1 : error2);
+				const err = command.errors.reduce(
```
Comment (StephenWeatherford) [inline src/mongo/commands.ts]: I thought you were just going to use the first one?

File: test/mongoGetCommand.test.ts [hunk 13]
```diff
@@ -214,4 +214,42 @@ suite("scrapbook parsing Tests", () => {
         let command = MongoCommands.getCommand(text, new Position(0, 0));
         assert.deepEqual(JSON.parse(command.arguments![0]), JSON.parse(arg0));
     });
+    test("test function call with erroneous syntax: missing comma", () => {
```
Comment (StephenWeatherford) [inline test/mongoGetCommand.test.ts]: Looks great

File: src/mongo/MongoCommand.ts [hunk 14]
```diff
@@ -12,4 +12,10 @@ export interface MongoCommand {
     name: string;
     // tslint:disable-next-line:no-banned-terms
     arguments?: string[];
+    errors?: errorDescription[];
+}
+
+interface errorDescription {
```
Comment (StephenWeatherford) [inline src/mongo/MongoCommand.ts]: Isn't there an error message?
