### PR TITLE
askForDocuments - throw error if no workspace found

### LINKED ISSUE #961: There shows a confused error message when running 'Import Document into a Collection' with no Workspace opened
**Platform / OS Version:**  Windows/ Mac / Linux
**Node.js** : V8.12.0
**Build Version:** [20181121.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=773&view=logs)

**Repro Steps:**
1. Make sure there is no warkspace opened.
2. Open Command Palette -> Type 'Import Document into a Collection' -> Run this command.
3. Check the result.

**Expect Experiment:**
There shows a clear error message.

**Actual Experiment:**
There shows a confused error message as below.
error

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #961. 
The vague error arises from showOpenDialog. Hence I'm performing a check and printing a better message instead.

### CODE REVIEW

File: src/commands/importDocuments.ts [hunk 1]
```diff
@@ -57,13 +57,17 @@ export async function importDocuments(uris: vscode.Uri[] | undefined, collection
 }
 
 async function askForDocuments(): Promise<vscode.Uri[]> {
+    let rootPath = vscode.workspace.rootPath;
+    if (!rootPath) {
+        throw new Error("No workspace found. Please open a workspace");
```
Comment (EricJizbaMSFT) [inline src/commands/importDocuments.ts]: I don't think this should block the user from importing documents. I'm pretty sure `defaultUri` is an optional parameter below or you could consider doing `os.homedir()` if it's not optional

Comment (PrashanthCorp) [reply src/commands/importDocuments.ts]: Sounds good.

File: src/commands/importDocuments.ts [hunk 2]
```diff
@@ -57,14 +57,18 @@ export async function importDocuments(uris: vscode.Uri[] | undefined, collection
...
 
 async function askForDocuments(): Promise<vscode.Uri[]> {
-    return await ext.ui.showOpenDialog({
+    let openDialogOptions: vscode.OpenDialogOptions = {
         canSelectMany: true,
         openLabel: "Import",
         filters: {
             "JSON": ["json"]
-        },
-        defaultUri: vscode.Uri.file(vscode.workspace.rootPath)
```
Comment (StephenWeatherford) [inline src/commands/importDocuments.ts]: 'Course, you could've just done this:

  defaultUri: vscode.workspace.rootPath ? vscode.Uri.file(vscode.workspace.rootPath) : undefined
