### PR TITLE
Fixed case issue for Postgres Stored Procedures

### LINKED ISSUE #1609: The name of the function does not match the input
**OS:** Mac
**Build Version:** 20200708.13

**Repro steps:**

1. Right click a PostgreSQL account.
2. Create a new database.
3. Right click  "Functions" node --> Click "Create Function Query…".
4. Provide function name and select return type.
5. Execute the query.
6. Check the result.

**Expect:**
The name of the function is the same as the input.

**Actual:**
The name of the function does not match the input.
Input:
image
Created:
image

### PR DESCRIPTION
**Pull request by neelip**
Fixes #1609

### CODE REVIEW

File: src/postgres/commands/createPostgresQuery/storedProcedure/steps/StoredProcedureQueryCreateStep.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export class StoredProcedureQueryCreateStep extends AzureWizardExecuteStep<IPost
     }
 }
 
-const defaultStoredProcedureQuery = (name: string) => `CREATE OR REPLACE PROCEDURE ${name}(/* arguments */)
+const defaultStoredProcedureQuery = (name: string) => `CREATE OR REPLACE PROCEDURE "${name}"(/* arguments */)
```
Comment (ejizba) [inline src/postgres/commands/createPostgresQuery/storedProcedure/steps/StoredProcedureQueryCreateStep.ts:22]: Use `wrapArgInQuotes`

**Review by ejizba — APPROVED** [review]
