### PR TITLE
showExplorer on cmd palette: Resolve collectionTreeItem to GraphTreeItem

### LINKED ISSUE #799: Error when trying to open GraphExplorer
Repro steps:
<Enter steps to reproduce issue>
I connected to my subscription and then went through selection boxes to select the graph database and the collection. In the end, I got below error. The query interface didn't open.

Action: cosmosDB.openGraphExplorer
Error type: TypeError
Error Message: node.treeItem.showExplorer is not a function

Version: 0.8.0
OS: win32

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #799

### CODE REVIEW

File: src/graph/registerGraphCommands.ts [hunk 1]
```diff
@@ -39,9 +39,15 @@ export function registerGraphCommands(context: vscode.ExtensionContext, tree: Az
         await node.deleteNode();
     });
     registerCommand('cosmosDB.openGraphExplorer', async (node: IAzureNode<GraphTreeItem>) => {
+        let treeItem: GraphTreeItem;
+        if (node) {
+            treeItem = node.treeItem;
+        }
         if (!node) {
```
Comment (StephenWeatherford) [inline src/graph/registerGraphCommands.ts]: else if

File: src/graph/registerGraphCommands.ts [hunk 2]
```diff
@@ -39,9 +39,15 @@ export function registerGraphCommands(context: vscode.ExtensionContext, tree: Az
...
-            node = <IAzureNode<GraphTreeItem>>await tree.showNodePicker(GraphCollectionTreeItem.contextValue);
+            let collectionNode = <IAzureNode<GraphCollectionTreeItem>>await tree.showNodePicker(GraphCollectionTreeItem.contextValue);
+            let children = await collectionNode.treeItem.loadMoreChildren(collectionNode, false);
+            treeItem = <GraphTreeItem>(children[0]);
```
Comment (StephenWeatherford) [inline src/graph/registerGraphCommands.ts]: I believe the right way to do this is:

1) pass in GraphTreeItem to showNodePicker
2) Add it to GraphAccountTreeItem.isAncestorOf
3) Implement GraphCollectionTreeItem.pickTreeItem\

It's possible this might not work because of the fact that we don't want to show the final leaf node, but I think it will work.

File: src/graph/tree/GraphCollectionTreeItem.ts [hunk 3]
```diff
@@ -75,4 +78,21 @@ export class GraphCollectionTreeItem implements IAzureTreeItem {
             throw new UserCancelledError();
         }
     }
+
+    public pickTreeItem?(expectedContextValue: string): IAzureTreeItem | undefined {
+        switch (expectedContextValue) {
+            case DocDBDocumentsTreeItem.contextValue:
```
Comment (StephenWeatherford) [inline src/graph/tree/GraphCollectionTreeItem.ts]: Why are DocDBDocument{,s}TreeItem here?
