### PR TITLE
Fix username validation for restricted usernames

### LINKED ISSUE #1756: There is no validation for the invalid Administrator Username "Admin" when creating PostgreSQL server
**OS:** All
**Build Version:** 20201126.3

**Repro Steps:**
F1 -> Azure Databases: Create Server... -> PostgreSQL -> Enter a valid server name -> Enter "Admin" as the Administrator Username.

**Expect:**
There is a validation for this invalid Administrator Username, like the validation in portal.
image

**Actual:**
There is no validation for this invalid Administrator Username.
image

**More Info:**
1. An error pops up when creating PostgreSQL server with the invalid Administrator Username “Admin”.
image
2. This issue does not reproduce in portal.
3. This issue does not reproduce for the invalid Administrator Username with "admin".
image
4. This issue also reproduces for other invalid Administrator Usernames, such as "Root/admiN...".

### PR DESCRIPTION
**Pull request by neelip**
Fixes #1756

### CODE REVIEW

File: src/postgres/commands/createPostgresServer/steps/PostgresServerCredUserStep.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ async function validateUser(username: string): Promise<string | undefined> {
         return localize('usernameBeginningMatch', 'The name cannot start with a number.');
     } else if (username.startsWith('pg_')) {
```
Comment (ejizba) [inline src/postgres/commands/createPostgresServer/steps/PostgresServerCredUserStep.ts:42]: What about this check - do we need to do `toLowerCase` to prevent people from starting with "PG_"?

**Review by ejizba — APPROVED** [review]

File: src/postgres/commands/createPostgresServer/steps/PostgresServerCredUserStep.ts (hunk 1 above)
Comment (neelip) [reply src/postgres/commands/createPostgresServer/steps/PostgresServerCredUserStep.ts:42]: That's true, "PG_" needs to be lowercase as well. Both versions are considered to be part of the restricted group.
