### PR TITLE
Fix handling of CRLF and add some unit tests, fixes #386

### LINKED ISSUE #386: Can only run the first command in a Mongo Scrapbook on Windows
As far as I can tell, this only repros on Windows

Repro steps:
1. Connect to a DB
1. Open a mongo scrapbook
1. Add two commands:
```
db.test.find()
db.test.findOne()
```
1. Put your cursor in the second command
1. Execute command

Expected: Results of findOne are displayed
Actual: Results of find are displayed

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Also improved some of the error messages for the scrapbook

### CODE REVIEW

**Comment by StephenWeatherford** [comment]
Also improved some of the error messages for the scrapbook

File: src/mongo/commands.ts [hunk 1]
```diff
@@ -22,13 +22,14 @@ export class MongoCommands {
...
 		if (activeEditor.document.languageId !== 'mongo') {
+			vscode.window.showInformationMessage("This command can only be run inside of a MongoDB scrapbook (*.mongo)");
 			return;
 		}
 		const selection = activeEditor.selection;
 		const command = MongoCommands.getCommand(activeEditor.document.getText(), selection.start);
 		if (command) {
 			if (!database) {
-				throw new Error('Please connect to the database first');
+				throw new Error('Please select a MongoDB database to run against by selecting it in the explorer and selecting the "Connect" context menu item');
```
Comment (EricJizbaMSFT) [inline src/mongo/commands.ts]: Just an idea: rather than throwing an error, we could show a warning message that has a 'Select database' button that calls `await vscode.commands.executeCommand('cosmosDB.connectMongoDB');`. It would use the node picker to select the db.

You'd have to make sure the command returned the connectDb so that you had access here, but I'm pretty sure that would be easy to do

File: test/mongoGetCommand.test.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
+/*---------------------------------------------------------------------------------------------
```
Comment (EricJizbaMSFT) [inline test/mongoGetCommand.test.ts]: woo
