### PR TITLE
Fix creating account in command palette

### LINKED ISSUE #495: Properties return undefined when trying to create an account through cmd palette
Repro steps:
1. ) Command palette > Cosmos DB: Delete Stored Procedure or Delete Account
2. ) Select subscription
3.) Select + Create New Account

Action: cosmosDB.deleteStoredProcedure
Error type: TypeError
Error Message: Cannot read property 'properties' of undefined

Version: 0.6.0
OS: win32

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
And hide stored procedure command since we're not shipping them yet

Fixes #495

### CODE REVIEW

File: src/tree/CosmosDBAccountProvider.ts [hunk 1]
```diff
@@ -54,12 +54,13 @@ export class CosmosDBAccountProvider implements IChildProvider {
             ],
             wizardContext);
 
+        // https://github.com/Microsoft/vscode-azuretools/issues/120
```
Comment (StephenWeatherford) [inline src/tree/CosmosDBAccountProvider.ts]: I don't understand exactly what this is fixing.

Comment (StephenWeatherford) [reply src/tree/CosmosDBAccountProvider.ts]: Or at least how it relates to https://github.com/Microsoft/vscode-azuretools/issues/120

Comment (EricJizbaMSFT) [reply src/tree/CosmosDBAccountProvider.ts]: This fixes "Cannot read property 'properties' of undefined" when actionContext is undefined. The reason its undefined is because its not being passed in to createChild as described in that issue

File: package.json [hunk 2]
```diff
@@ -605,6 +605,10 @@
 				{
 					"command": "cosmosDB.loadMore",
 					"when": "never"
+				},
+				{
+					"command": "cosmosDB.deleteStoredProcedure",
+					"when": "never"
```
Comment (PrashanthCorp) [inline package.json]: Why have the command if we're not shipping stored procedures at this moment?

Comment (EricJizbaMSFT) [reply package.json]: I just did the smallest change I could to hide stored procedures code. I don't wanna completely remove it and change a lot of code

File: src/tree/CosmosDBAccountProvider.ts (hunk 1 above)
Comment (StephenWeatherford) [reply src/tree/CosmosDBAccountProvider.ts]: But it's being passed as a dummy, so we won't be getting the proper telemetry, right?

Comment (EricJizbaMSFT) [reply src/tree/CosmosDBAccountProvider.ts]: Yes that is correct. That's why I filed the issue in the shared package, but I never felt like a few missing telemetry properties was high enough priority to work on (Remember - this only happens if people run the command from the command palette)
