### PR TITLE
Fixed time out on connecting non existant items.

### LINKED ISSUE #2707: Connecting to a Non-Existent Host Never Times Out
When attempting to connect to an unreachable (non-existent) host, the connection attempt hangs indefinitely. There is no timeout, and the user has no way to abort the process.

### Steps to Reproduce

1. Create a local connection to a non-existent host:

    - Take the connection string from a working host and modify the domain to something invalid or unreachable.

2. Attempt to connect.

3. Observe that the connection attempt does not complete or fail — it just hangs. 🐌

### Expected Behavior

The connection attempt should timeout after a reasonable period or provide an option for the user to cancel.

Image

### PR DESCRIPTION
**Pull request by mkrueger**
Basically it just lowers too long timeouts and adds some error messages.

This pull request introduces improvements for handling connection timeouts and enhances code maintainability by centralizing HTTP status codes and timeout values. The most significant changes are the addition of a comprehensive `HttpStatusCodes` class, the introduction of the `CosmosDBTimeouts` class for managing connection timeouts, and the application of these timeouts to Cosmos DB credential verification logic. Additionally, new localized timeout error messages have been added.

**Timeout Handling and Error Messaging Improvements:**

- Added new localized strings for connection timeout error messages to `bundle.l10n.json`, improving user feedback when timeouts occur.
- Updated the Cosmos DB credential verification logic in `CosmosDBCredential.ts` to use a timeout when connecting to accounts, preventing indefinite hangs on unreachable hosts. If a timeout occurs, a specific error message is logged and user feedback is improved. [[1]](diffhunk://#diff-e2d1f60a078f50cae89212686bb3a7d7710b41f77ba5b837cf6de386a730edb1R10-R12) [[2]](diffhunk://#diff-e2d1f60a078f50cae89212686bb3a7d7710b41f77ba5b837cf6de386a730edb1L225-R249)

**Centralization of Constants:**

- Introduced a new `HttpStatusCodes` class in `constants.ts` that defines all standard HTTP status codes with documentation, improving code readability and maintainability.
- Added a `CosmosDBTimeouts` class in `constants.ts` to centralize timeout values for emulator and remote Cosmos DB connections, making it easier to adjust and reference these values throughout the codebase.
- Updated imports in relevant files (`CosmosDBCredential.ts`, `CosmosDBAccountAttachedResourceItem.ts`) to use the new `CosmosDBTimeouts` class. [[1]](diffhunk://#diff-e2d1f60a078f50cae89212686bb3a7d7710b41f77ba5b837cf6de386a730edb1R10-R12) [[2]](diffhunk://#diff-ebdfd45c24630c4fc29a68e1218482ad287fd28c8b7ac282a91435169bf1c91eL11-R11)

These changes collectively make the codebase more robust against network issues and easier to maintain regarding HTTP codes and timeout configurations.

Fixes  #2707

### CODE REVIEW

File: src/tree/cosmosdb/CosmosDBAccountAttachedResourceItem.ts [hunk 1]
```diff
@@ -27,6 +27,16 @@ export abstract class CosmosDBAccountAttachedResourceItem
 {
     declare public readonly account: CosmosDBAttachedAccountModel;
 
+    /**
+     * Connection timeout for emulators (shorter since they should respond quickly if running)
+     */
+    private static readonly EMULATOR_CONNECTION_TIMEOUT_MS = 1000;
```
Comment (sevoku) [inline src/tree/cosmosdb/CosmosDBAccountAttachedResourceItem.ts]: Should this be in `constants.ts` and be referenced from here and also from `CosmosDBCredential.ts`?

File: l10n/bundle.l10n.json [hunk 2]
```diff
@@ -1,12 +1,7 @@
 {
-  " (Press 'Space' to select and 'Enter' to confirm)": " (Press 'Space' to select and 'Enter' to confirm)",
```
Comment (sevoku) [inline l10n/bundle.l10n.json:2]: These loc changes don't seem to be related and break the build.

**Review by sevoku — CHANGES_REQUESTED** [review]

File: l10n/bundle.l10n.json (hunk 2 above)
Comment (mkrueger) [reply l10n/bundle.l10n.json:2]: IDK where they're from but npm l10n insists on them  so they'll be generated sooner or later.

File: src/tree/cosmosdb/CosmosDBAccountAttachedResourceItem.ts (hunk 1 above)
Comment (mkrueger) [reply src/tree/cosmosdb/CosmosDBAccountAttachedResourceItem.ts]: + moved it.

We've a mess of different timeouts all over the place - would be nice to introduce some constants for it there.

File: l10n/bundle.l10n.json (hunk 2 above)
Comment (mkrueger) [reply l10n/bundle.l10n.json:2]: reinstalled node.js/npm fixed that. now I've a bit older version.

**Comment by sevoku** [comment]
@mkrueger the build still fails.
