### PR TITLE
Log info for deleting cosmos account

### LINKED ISSUE #1544: There is no log "Successfully deleted server..."
**OS:** All
**Build Version:** 20200527.16

**Repro Steps:**

1. Delete a server account.
2. Create a new server account while deleting the above server account.
3. Check output log.

**Expect:**
There is a log "Successfully deleted server...", such as:
image

**Actual:**
There is no log "Successfully deleted server...".
image

### PR DESCRIPTION
**Pull request by neelip**
Fixes #1544

### CODE REVIEW

File: src/commands/deleteCosmosDBAccount.ts [hunk 1]
```diff
@@ -21,7 +22,9 @@ export async function deleteCosmosDBAccount(node: AzureTreeItem): Promise<void>
             await client.databaseAccounts.deleteMethod(resourceGroup, accountName);
         });
         // don't wait
```
Comment (wwlorey) [inline src/commands/deleteCosmosDBAccount.ts:24]: nit: it makes sense to keep this "don't wait" by the `showInformationMessage` call if we even need to keep it at all

Comment (neelip) [reply src/commands/deleteCosmosDBAccount.ts]: might not need it actually
