### PR TITLE
Document Update : throw error if doc ID is not found.

### LINKED ISSUE #126: Update mongo document doesn't throw error if id is not found
Repro steps:
1. Open a mongo document
1. Edit _id to an id that doesn't exist
1. Update to Azure

Expected: Error saying we could not find that id
Actual: No error

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #126

### CODE REVIEW

File: src/mongo/tree/MongoDocumentTreeItem.ts [hunk 1]
```diff
@@ -64,7 +64,10 @@ export class MongoDocumentTreeItem implements IAzureTreeItem {
 
     public static async update(collection: Collection, newDocument: IMongoDocument): Promise<IMongoDocument> {
         const filter: object = { _id: new ObjectID(newDocument._id) };
-        await collection.updateOne(filter, _.omit(newDocument, '_id'));
+        const result = await collection.updateOne(filter, _.omit(newDocument, '_id'));
+        if (result.upsertedCount != 1) {
+            throw new Error("Document not found. Please check if ID exists.");
```
Comment (EricJizbaMSFT) [inline src/mongo/tree/MongoDocumentTreeItem.ts]: We don't know if "Document not found" is the reason it failed. It could have been any number of reasons.

What if we generalize it a little bit: ``Failed to update document with _id "${newDocument._id}".``

File: src/mongo/tree/MongoDocumentTreeItem.ts [hunk 2]
```diff
@@ -66,7 +66,7 @@ export class MongoDocumentTreeItem implements IAzureTreeItem {
         const filter: object = { _id: new ObjectID(newDocument._id) };
         const result = await collection.updateOne(filter, _.omit(newDocument, '_id'));
         if (result.upsertedCount != 1) {
-            throw new Error("Document not found. Please check if ID exists.");
+            throw new Error(`Failed to update document with _id ${newDocument._id}.`);
```
Comment (StephenWeatherford) [inline src/mongo/tree/MongoDocumentTreeItem.ts]: Put quotes around the ID.
