### PR TITLE
Fix mongo createCollection

### LINKED ISSUE #113: Mongo CreateCollection fails if a collection already exists in the DB
This essentially limits the database from having more than one collection.

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
Fixes #113

### CODE REVIEW

File: src/mongo/nodes.ts [hunk 1]
```diff
@@ -131,12 +131,14 @@ export class MongoDatabaseNode implements INode {
...
-	createCollection(collectionName: string): Promise<MongoCollectionNode> {
-		return this.getDb()
-			.then(db => db.createCollection(collectionName))
-			.then(collection => {
-				return new MongoCollectionNode(collection, this);
-			});
+	async createCollection(collectionName: string): Promise<MongoCollectionNode> {
+		const db: Db = await this.getDb();
+		const newCollection: Collection = db.collection(collectionName);
+		// db.createCollection() doesn't create empty collections for some reason
```
Comment (PrashanthCorp) [inline src/mongo/nodes.ts]: Interesting. Didn't notice this quirk. Nice catch!
