### PR TITLE
Fix '(Connected)' label bugs

### LINKED ISSUE #481: Persisted connected node does not display Connected in its label on startup

### LINKED ISSUE #487: Refreshing Mongo Account removes '(Connected)' from database node
Repro Steps:
1. Connect to a mongo database
1. Refresh the mongo account node

Expected:
Database node still has '(Connected)' in label

Actual:
Database node does _not_ have '(Connected)' in label, but it technically still is connected (commands in the scrapbook still work)

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
Fixes #487 
Fixes #481 

Requires this PR: https://github.com/Microsoft/vscode-azuretools/pull/148

### CODE REVIEW

File: src/mongo/registerMongoCommands.ts [hunk 1]
```diff
@@ -44,23 +47,20 @@ export function registerMongoCommands(context: vscode.ExtensionContext, actionHa
...
-        connectedDb = node;
-        await languageClient.connect(connectedDb.treeItem.connectionString, connectedDb.treeItem.databaseName);
-        connectedDb.treeItem.isConnected = true;
-        await node.refresh();
+
+        await languageClient.connect(node.treeItem.connectionString, node.treeItem.databaseName);
         context.globalState.update(connectedDBKey, node.id);
+        ext.connectedMongoDB = node;
+
+        await tree.refresh(node.parent);
```
Comment (StephenWeatherford) [inline src/mongo/registerMongoCommands.ts]: Don't think this will handle the case where you're switching the connection from an Azure node to an attached node?

File: src/mongo/registerMongoCommands.ts [hunk 2]
```diff
@@ -86,20 +86,21 @@ export function registerMongoCommands(context: vscode.ExtensionContext, actionHa
...
+        await MongoCommands.executeCommandFromActiveEditor(<IAzureParentNode<MongoDatabaseTreeItem>>ext.connectedMongoDB, context.extensionPath, editorManager, tree, this);
     });
 }
 
+async function loadPersistedMongoDB(context: vscode.ExtensionContext, tree: AzureTreeDataProvider): Promise<void> {
+    const persistedNodeId: string | undefined = context.globalState.get(connectedDBKey);
+    if (persistedNodeId) {
+        const persistedNode: IAzureNode | undefined = await tree.findNode(persistedNodeId);
+        if (persistedNode) {
+            await vscode.commands.executeCommand('cosmosDB.connectMongoDB', persistedNode);
```
Comment (StephenWeatherford) [inline src/mongo/registerMongoCommands.ts]: What if this fails?

File: src/mongo/registerMongoCommands.ts (hunk 1 above)
Comment (EricJizbaMSFT) [reply src/mongo/registerMongoCommands.ts]: Good point

File: src/mongo/registerMongoCommands.ts (hunk 2 above)
Comment (EricJizbaMSFT) [reply src/mongo/registerMongoCommands.ts]: It feels like worst case you just don't get the 'persisted' behavior and you have to reconnect? Can you think of anything worse? That doesn't seem too bad to me

File: src/mongo/tree/MongoDatabaseTreeItem.ts [hunk 3]
```diff
@@ -20,24 +21,30 @@ export class MongoDatabaseTreeItem implements IAzureParentTreeItem {
...
 	public readonly databaseName: string;
 
-	public isConnected: boolean = false;
+	private _isConnected: boolean;
 
-	constructor(databaseName: string, connectionString: string) {
+	constructor(databaseName: string, connectionString: string, parentId: string) {
 		this.databaseName = databaseName;
 		this.connectionString = connectionString;
+		this._isConnected = ext.connectedMongoDB && ext.connectedMongoDB.id === `${parentId}/${databaseName}`;
```
Comment (StephenWeatherford) [inline src/mongo/tree/MongoDatabaseTreeItem.ts]: Seems like you could get rid of setting _isConnected here if you turned it into a property get. Then also wouldn't need refreshLabel.

File: src/extensionVariables.ts [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+ *  Licensed under the MIT License. See License.txt in the project root for license information.
+ *--------------------------------------------------------------------------------------------*/
+
+import { IAzureNode } from "vscode-azureextensionui";
+
+/**
+ * Namespace for common variables used throughout the extension. They must be initialized in the activate() method of extension.ts
+ */
+export namespace ext {
+    export let connectedMongoDB: IAzureNode | undefined;
```
Comment (StephenWeatherford) [inline src/extensionVariables.ts]: Do you actually need to keep a reference to the node instead of just the ID?  Would keeping only the ID break your dependency and allow you to reduce the complexity?

File: src/mongo/registerMongoCommands.ts (hunk 2 above)
Comment (StephenWeatherford) [reply src/mongo/registerMongoCommands.ts]: You're awaiting it in execute, so it will fail every time.

File: src/extensionVariables.ts (hunk 4 above)
Comment (EricJizbaMSFT) [reply src/extensionVariables.ts]: I need the node to fix your other comment :) (making sure I refresh the "old" node in case you switch from Azure to Attached)

Comment (StephenWeatherford) [reply src/extensionVariables.ts]: Can you search for the node?

Comment (StephenWeatherford) [reply src/extensionVariables.ts]: Doesn't matter much if this doesn't reduce complexity.

Comment (EricJizbaMSFT) [reply src/extensionVariables.ts]: Yes, but that feels more complex and slower than just keeping a reference to the node IMO

File: src/mongo/registerMongoCommands.ts (hunk 2 above)
Comment (EricJizbaMSFT) [reply src/mongo/registerMongoCommands.ts]: Can expand on that? I don't know what you mean...are you confusing `cosmosDB.executeMongoCommand` or `MongoCommands.executeCommandFromActiveEditor` with `vscode.commands.executeCommand`

Comment (EricJizbaMSFT) [reply src/mongo/registerMongoCommands.ts]: Never mind - I get you

Comment (EricJizbaMSFT) [reply src/mongo/registerMongoCommands.ts]: Fixed

File: src/mongo/tree/MongoDatabaseTreeItem.ts (hunk 3 above)
Comment (EricJizbaMSFT) [reply src/mongo/tree/MongoDatabaseTreeItem.ts]: Done

File: src/mongo/registerMongoCommands.ts [hunk 5]
```diff
@@ -44,23 +48,24 @@ export function registerMongoCommands(context: vscode.ExtensionContext, actionHa
...
-        connectedDb = node;
-        await languageClient.connect(connectedDb.treeItem.connectionString, connectedDb.treeItem.databaseName);
-        connectedDb.treeItem.isConnected = true;
-        await node.refresh();
+
+        const oldNode: IAzureNode | undefined = ext.connectedMongoDB;
+        await languageClient.connect(node.treeItem.connectionString, node.treeItem.databaseName);
         context.globalState.update(connectedDBKey, node.id);
+        ext.connectedMongoDB = node;
+        await tree.refresh(node.parent);
```
Comment (StephenWeatherford) [inline src/mongo/registerMongoCommands.ts]: nit: I thought there was a way to refresh a node's label...?

File: src/mongo/tree/MongoDatabaseTreeItem.ts [hunk 6]
```diff
@@ -20,20 +21,22 @@ export class MongoDatabaseTreeItem implements IAzureParentTreeItem {
...
 	}
 
 	public get label(): string {
-		if (this.isConnected) {
-			return this.databaseName + " (Connected)";
-		}
 		return this.databaseName;
 	}
 
+	public get description(): string {
```
Comment (StephenWeatherford) [inline src/mongo/tree/MongoDatabaseTreeItem.ts]: Might be worth considering to add a fullId property to nodes at some point...

Comment (EricJizbaMSFT) [reply src/mongo/tree/MongoDatabaseTreeItem.ts]: There is, but it's only at the 'node' level, not the 'treeItem' level

File: src/mongo/registerMongoCommands.ts [hunk 7]
```diff
@@ -44,23 +48,24 @@ export function registerMongoCommands(context: vscode.ExtensionContext, actionHa
...
+        }
     });
     actionHandler.registerCommand('cosmosDB.deleteMongoDB', async (node?: IAzureNode<MongoDatabaseTreeItem>) => {
         if (!node) {
             node = <IAzureNode<MongoDatabaseTreeItem>>await tree.showNodePicker(MongoDatabaseTreeItem.contextValue);
         }
         await node.deleteNode();
-        if (connectedDb && connectedDb.treeItem.id === node.treeItem.id) {
-            connectedDb = null;
+        if (ext.connectedMongoDB && ext.connectedMongoDB.id === node.id) {
```
Comment (StephenWeatherford) [inline src/mongo/registerMongoCommands.ts]: Also need this in detach.  Although not sure there's anything bad that happens if it's not done?

Comment (EricJizbaMSFT) [reply src/mongo/registerMongoCommands.ts]: Filed a separate issue: https://github.com/Microsoft/vscode-cosmosdb/issues/492

Don't feel like fixing in this PR and it was always a problem before my changes

File: src/mongo/tree/MongoDatabaseTreeItem.ts (hunk 6 above)
Comment (StephenWeatherford) [reply src/mongo/tree/MongoDatabaseTreeItem.ts]: Ideally there'd be a way to refresh the entire tree's labels only.

Comment (EricJizbaMSFT) [reply src/mongo/tree/MongoDatabaseTreeItem.ts]: Fair enough. Doesn't exist yet

**Comment by EricJizbaMSFT** [comment]
Thanks @StephenWeatherford for sticking with me through this PR haha 😊
