### PR TITLE
Success and progress notifications/log messages for PostgreSQL

### LINKED ISSUE #1502: [Suggestion] Add the log info when deleting a database
**OS:** All
**Build Version:** 20200522.22

**Repro Steps:**
Delete a database from any account.

**Actual:**
There is no log info when deleting a database.

**Suggestion:**
Add the log info when deleting a database.

**More info:**
1. This issue also reproduces when deleting collection, document....
2. There is notification message when deleting an account but no log in output.

### PR DESCRIPTION
**Pull request by neelip**
Fixes #1502

### CODE REVIEW

File: src/postgres/commands/enterPostgresCredentials.ts [hunk 1]
```diff
@@ -32,7 +32,22 @@ export async function enterPostgresCredentials(context: IActionContext, treeItem
         validateInput: (value: string) => { return (value && value.length) ? undefined : localize('passwordCannotBeEmpty', 'Password cannot be empty.'); }
     });
 
-    const server: Server = nonNullProp(treeItem, 'server');
-    await setPostgresCredentials(username, password, nonNullProp(server, 'id'));
+    const serverName: string = nonNullProp(treeItem.server, 'name');
+    const id: string = nonNullProp(treeItem.server, 'id');
+
+    const progressMessage: string = localize('setupCredentialsMessage', 'Setting up Credentials for server "{0}"...', serverName);
```
Comment (wwlorey) [inline src/postgres/commands/enterPostgresCredentials.ts:38]: nit: small capitalization fix
```suggestion
    const progressMessage: string = localize('setupCredentialsMessage', 'Setting up credentials for server "{0}"...', serverName);
```
