### PR TITLE
Fix Partition Key handling

### LINKED ISSUE #2764: Incorrect Validation Rule for Null Values in Cosmos DB Partition Key with Azure Tools for Visual Studio Code
If you try to save a JSON record that sets a property associated with the Partition Key with a Null value, the edition displays a validation error and disables the save option.

For example, if you have a container that has "ClientId" as a Partition Key for your container, and you try to save this in Visual Studio New Item tab:

```
{
  "ClientId": null,
  "ScopeType": "global",
  "ModifiedBy": "app"
}
```

A red box appears at top that says:

> > This item contains 1 validation error. Please fix them before saving.
> Partition key ClientId is invalid.

**Excepted behavior:**
In the Azure Portal, Cosmos DB section, you can add the same JSON because Cosmos DB supports Null values in a Partition key.

### PR DESCRIPTION
**Pull request by sevoku**
This pull request introduces several improvements and refactorings related to Cosmos DB document partition key handling, document session management, and user confirmation dialogs for deletion actions. The changes enhance partition key update support, clarify user prompts, and improve data structures for document identification in the UI.
In addition this properly renders `null` and `undefined` values as well as special empty obejcts with `{}` for `None` partition keys:
image

### Partition Key Handling and Document Update Logic

* Refactored partition key extraction and comparison in `DocumentSession`, enabling support for updating documents where the partition key value changes. This now performs a delete-and-create operation when the partition key changes. [[1]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07R208-R266) [[2]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07L214-R289)
* Updated partition key validation logic to allow for optional validation via a new `allowNullOrUndefinedPartitionKey` parameter, making partition key checks more flexible for UI-driven imports. [[1]](diffhunk://#diff-dba1eda57fd7e8b33c84d1801e2cc328127d5326d2483e7a47a601f41a366d2fL11-R15) [[2]](diffhunk://#diff-dba1eda57fd7e8b33c84d1801e2cc328127d5326d2483e7a47a601f41a366d2fL23-R27) [[3]](diffhunk://#diff-dba1eda57fd7e8b33c84d1801e2cc328127d5326d2483e7a47a601f41a366d2fR52-R54)
* Added utility functions in `convertors.ts` to detect "None" partition key values and empty objects, improving partition key value handling.

### Document Session and Data Structure Improvements

* Enhanced types for table and tree data records to include `CosmosDBRecordIdentifier`, making it easier to track and operate on documents in the UI and backend. [[1]](diffhunk://#diff-58cc5c765c72f86b21c2cf2e270040ae521edbb242645ed484107e77f47a7286L23-R45) [[2]](diffhunk://#diff-58cc5c765c72f86b21c2cf2e270040ae521edbb242645ed484107e77f47a7286R233) [[3]](diffhunk://#diff-58cc5c765c72f86b21c2cf2e270040ae521edbb242645ed484107e77f47a7286R206)
* Updated usages throughout `DocumentSession` to consistently use `containerPartitionKey` and improved extraction and propagation of partition key values when posting document events. [[1]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07R98-R102) [[2]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07L108-R112) [[3]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07L168-R177) [[4]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07L400-R482) [[5]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07L426-R503)

### User Confirmation Dialog Improvements

* Improved deletion confirmation dialogs: single-item and bulk delete actions now display context-appropriate prompts, and new localized strings were added for clarity. [[1]](diffhunk://#diff-829b512e02461234524c007941f3260e67a43b109f48bedf257ab8e8033cc527L61-R63) [[2]](diffhunk://#diff-829b512e02461234524c007941f3260e67a43b109f48bedf257ab8e8033cc527R167) [[3]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07R319-R328) [[4]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07L312-R390)

### Miscellaneous

* Minor import and type definition cleanups for clarity and maintainability, including new imports and removal of unused ones. [[1]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07R16) [[2]](diffhunk://#diff-58cc5c765c72f86b21c2cf2e270040ae521edbb242645ed484107e77f47a7286L13-R18) [[3]](diffhunk://#diff-2fb79783974e66910933012f3b9cd17657ee6aec135e555c54112adb7fa56f07L28-R29)

These changes collectively make partition key handling more robust, improve user experience for document deletion, and simplify document identification throughout the codebase.

Fixes #2764

### CODE REVIEW

File: src/cosmosdb/session/DocumentSession.ts [hunk 1]
```diff
@@ -201,35 +205,96 @@ export class DocumentSession {
...
-                        id: record.id,
-                        _rid: record._rid,
-                        partitionKey: partitionKey ? extractPartitionKey(record, partitionKey) : undefined,
-                    };
+                if (partitionKeyChanged) {
+                    // Partition key has changed - need to delete old item and create new one
+                    context.telemetry.properties.partitionKeyChanged = 'true';
+
+                    // Delete the old item
+                    await this.client
```
Comment (bk201-) [inline src/cosmosdb/session/DocumentSession.ts]: await this.delete()
await this.create() ?

Comment (sevoku) [reply src/cosmosdb/session/DocumentSession.ts]: Good point, although `this.delete()` will prompt for confirmation. I'll refactor it a little bit and add a new partition key changed confirmation.

Comment (sevoku) [reply src/cosmosdb/session/DocumentSession.ts]: Done [e45d0be](https://github.com/microsoft/vscode-cosmosdb/pull/2787/commits/e45d0bed52be35ace461515f742134ff14e5a1fd)
