### PR TITLE
Inform user to start emulator on timeout(SQL) or specific error(Mongo)

### LINKED ISSUE #706: [Windows][Mongo] We need a better error message if emulator not started

### LINKED ISSUE #873: [SQL][Emulator] Expanding the tree item when emulator not installed leads to a long delay before error message
The main issue is that the documentClient is unable to hit the given endpoint, waits a full seconds, and retries another 120 times. This amounts to at least 2 minutes, and that is not good. 
This happens _instead_ of a thrown error (even on await), and hence a simple try catch with async await will not work. 

Ideally, this should be fixed along with the other emulator bug.

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #706 
Fixes #873

### CODE REVIEW

File: src/docdb/tree/DocDBAccountTreeItemBase.ts [hunk 1]
```diff
@@ -81,6 +82,11 @@ export abstract class DocDBAccountTreeItemBase extends DocDBTreeItemBase<Databas
         throw new UserCancelledError();
     }
 
+    public async loadMoreChildrenImpl(clearCache: boolean) {
+        let unableToReachEmulatorMessage: string = "Unable to reach emulator. Please ensure it is started and writing to the appropriate port. Then try again.";
+        return await rejectOnTimeout(2000, () => super.loadMoreChildrenImpl(clearCache), unableToReachEmulatorMessage);
```
[the remark this answers is not in the document]
Comment (PrashanthCorp) [reply src/docdb/tree/DocDBAccountTreeItemBase.ts]: I should have wrapped this inside an isEmulator flag if possible. 
I'm saying that an account fetching a list of databases shouldn't be more that 2 seconds. I'll admit that I forgot to confine this to emulators (my testing of your graph account didn't show this miscalculation on my part).

File: src/mongo/tree/MongoAccountTreeItem.ts [hunk 2]
```diff
@@ -73,7 +73,14 @@ export class MongoAccountTreeItem extends AzureParentTreeItem<IMongoTreeRoot> {
             return databases
                 .filter((database: IDatabaseInfo) => !(database.name && database.name.toLowerCase() === "admin" && database.empty)) // Filter out the 'admin' database if it's empty
                 .map(database => new MongoDatabaseTreeItem(this, database.name, this.connectionString));
-        } finally {
+        } catch (error) {
+            let message = parseError(error).message;
+            if (this._root.isEmulator && message.includes("ECONNREFUSED")) {
+                error.message = "Unable to reach emulator. Please ensure it is started and writing to the appropriate port. Then try again.";
```
Comment (StephenWeatherford) [inline src/mongo/tree/MongoAccountTreeItem.ts]: Still not really happy with this approach, although I understand the logic. If you're going to use it, at least add the original message to the end, thanks.

Ideally we'd have a common util to do this properly.

File: src/utils/timeout.ts [hunk 3]
```diff
@@ -24,12 +24,12 @@ export async function valueOnTimeout<T>(timeoutMs: number, timeoutValue: T, acti
 /**
  * Returns the result of awaiting a specified action. Rejects if the action throws or if the time-out occurs.
  */
-export async function rejectOnTimeout<T>(timeoutMs: number, action: () => Promise<T> | T) {
+export async function rejectOnTimeout<T>(timeoutMs: number, action: () => Promise<T> | T, callerTimeOutError?: string) {
```
Comment (StephenWeatherford) [inline src/utils/timeout.ts]: callerTimeOutMessage

It would actually be useful in the future to allow an Error object, but for now please be more specific about what it is, thanks.

File: src/mongo/tree/MongoAccountTreeItem.ts (hunk 2 above)
Comment (PrashanthCorp) [reply src/mongo/tree/MongoAccountTreeItem.ts]: Do you prefer this PR to add a common util of the form: 
```
prefixErrorWithMessage(error, message) ..

appendErrorWithMessage(error, message)...
```

Comment (StephenWeatherford) [reply src/mongo/tree/MongoAccountTreeItem.ts]: Would love to see that, yeah.  How about nestError(errorish: unknown, mainMessage: string)

File: src/docdb/tree/DocDBAccountTreeItemBase.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (StephenWeatherford) [reply src/docdb/tree/DocDBAccountTreeItemBase.ts]: Okay. :-)  Still, you should restrict the timeout to emulator. Networks can be slow or down, and the current code will say the emulator's at fault no matter what.

[the remark this answers is not in the document]
Comment (PrashanthCorp) [reply src/docdb/tree/DocDBAccountTreeItemBase.ts]: Fixed this in the subsequent push
