### PR TITLE
Re-opening VSCode multiple times now shouldn't break update document

### LINKED ISSUE #370: Failed to update mongo document after closing and re-opening VS Code multiple times
1. Open a mongo document
1. Close vscode
1. Open vscode
1. Open a mongo collection
1. Close vscode
1. Open vscode
1. Try to update the mongo _document_

Expected:
It works

Actual:
It fails with this error:
screen shot 2018-02-23 at 2 57 17 pm

I believe it's because we change the persistence to only include the mongo collection and then we lose persistence of the mongo document.

### PR DESCRIPTION
**Pull request by PrashanthCorp**
Fixes #370

### CODE REVIEW

File: src/CosmosEditorManager.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ export class CosmosEditorManager {
             }
         }
         this.fileMap[localDocPath] = editor;
-        const fileMapLabels = {};
+        const fileMapLabels = this._globalState.get(this._persistedEditorsKey);
```
Comment (EricJizbaMSFT) [inline src/CosmosEditorManager.ts]: Hahaha didn't we just learn that this can return undefined? 🙃

You could just do `const fileMapLabels = this._globalState.get(this._persistedEditorsKey) || {};`

Comment (StephenWeatherford) [reply src/CosmosEditorManager.ts]: Yep, you should think about stuff like this always.

BTW, have you searched for other uses of this._globalState.get() that might cause problems?

Comment (PrashanthCorp) [reply src/CosmosEditorManager.ts]: @EricJizbaMSFT I'm going with [get<T>(key: string, defaultValue: T): T](https://code.visualstudio.com/docs/extensionAPI/vscode-api#Memento) - that looks cleaner and more official to me. 

@StephenWeatherford - Looked at issues filed and StackOverflow, I don't see anything surprising so far.

Comment (StephenWeatherford) [reply src/CosmosEditorManager.ts]: @PrashanthCorp I was referring to if you've checked all uses of globalState.get() in our code...
